# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

# hello_world:
#   en: Hello world !
#   fr: Bonjour le monde !
home_page:
  en: Home
  ru: Домой
read_more:
  en: Read More
  ru: Подробности
en:
  ru: Русский
  en: English

ru:
  en: Russia 
  ru: Русский
